[global]
watermark_password = myPa7&KPswZ)8F6d12!@p_9
p = 3
psnr = 40.0
display_fps = true

[compute]
; OpenCL only: select device
opencl_device_id = 0
; CUDA only: NVDEC video hardware decoding and decoding options (can be mixed)
cuda_hw_decoder = h264_cuvid
cuda_hw_encoder = true

[image]
; single: embed on the "path" image (must be a file) and detect it
; batch_embed: embed ME watermark on all images found under "path" (must be a directory)
; batch_detect: try to detect ME watermark on all images found under "path" (must be a directory)
mode = single
path = samples/images/4k.png
save_to_disk = false
; set this value to benchmark image watermarking by simulating more work
benchmark_loops = 1000

[video]
; path = samples/videos/sample_1080p.mkv
; "embed" or "detect"
mode = embed
; embed video output path
encode_output_path = samples/videos/sample_1080p_watermarked.mkv
; encode CPU only options
encode_codec_options = -c:v libx265 -preset fast -crf 23
; encode CUDA only options, overwrite "encode_codec_options" if set AND "cuda_hw_encoder" is true, else it is ignored
hw_encode_options = -c:v hevc_nvenc -preset p6 -tune hq -cq 26 -b:v 0
; set this value to encode/decode the watermark after X frames. This improves quality of the video and encoding speed
watermark_interval = 30