[global]
watermark_data_file = samples/w_4k.dat
p = 3
psnr = 40.0
display_fps = true

[compute]
; OpenCL only: select device
opencl_device_id = 1
; CUDA only: NVDEC video hardware acceleration
cuda_hw_decoder = hevc_cuvid

[image]
path = samples/images/4k.png
save_to_disk = false
; set this value to benchmark image watermarking by simulating more work
benchmark_loops = 1000

[video]
; path = samples/videos/sample_1080p.mkv
; "embed" or "detect"
mode = embed
; embed/encode only options
encode_output_path = samples/videos/sample_1080p_watermarked.mkv
encode_codec_options = -c:v libx265 -preset fast -crf 23
; set this value to encode/decode the watermark after X frames. This improves quality of the video and encoding speed
watermark_interval = 30